---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: ../../environments
  roles_path: ../../roles
  cookbooks_path: ../../cookbooks

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65

suites:
  - name: prod
    provisioner:
      client_rb:
        environment: production
    driver:
      network:
        - ["private_network", {ip: "192.168.33.41"}]
    run_list:
      - recipe[apache::default]
      - role[webserver]
    attributes:

  - name: dev
    provisioner:
      client_rb:
        environment: dev
    driver:
      network:
        - ["private_network", {ip: "192.168.33.42"}]
    run_list:
      - recipe[apache::default]
      - role[webserver]
    attributes:
