name             'node'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures node'
long_description 'Installs/Configures node'
version          '0.2.0'
